"""gcheck: the validation checks behind autoeval_check.py.

    prompt_inputs/   group 1  prompt frame, occupation pairing, input file quality, uniqueness
    golden_rubric/   group 2  rubric form, negatives, landing, liveness, fidelity, sourcing, leakage
    authorship/      group 3  prose tells, package provenance, workbook shape
    packaging/       group 4  hygiene sweeps
    core.py          emit/recommend/debt, the @check registry, run_checks, selfcheck, --rules
    state.py         TaskState: the task folder plus every parse the run has made, once
    common.py        the one home for each helper shared by more than one module
    procedural.py    PR1-PR4, house rules with no detector
    driver.py        the submission-side runner (autoeval_check.py)

See tools/README.md for the layout, docs/rules.md (generated by `autoeval_check.py --rules`)
for every id's rule, and gate_families.py for the rule map every check id feeds.
"""
