"""De-batch a task package's document-property metadata.

    .venv/bin/python tools/fix_metadata.py <task-folder> [--check]

Why this exists (2026-08-31, review 9b44f1db + the task 21 rejection): a package
whose files share one docProps write instant, or ship python-docx's default
description string, carries the batch-generation signature reviewers and the
platform flag ("package-level provenance evidence of batch generation is a
rejection without a revision cycle", prompts/submission.md). Timestamps and the
description are document properties we author anyway, like the in-world creator
and title, so they are set deliberately per file.

What it does, per .xlsx/.docx under inputs/ and solution/:

- KEEPS every authored dcterms:created / dcterms:modified stamp as it is. Only
  when two files share the exact same instant does it shift the later files
  (sorted by name) by a deterministic handful of minutes, keeping the date and
  hour, so a rerun is idempotent and the in-world story survives.
- Empties a docx dc:description that still holds python-docx's default text
  ("generated by python-docx"). An authored description is left alone.
- Sets each file's filesystem mtime to its dcterms:modified instant, so the
  outer i-/s- zips stop stamping every member with one build instant.

What it must NEVER touch: docProps/app.xml. The Openpyxl generator string is
EVIDENCE under the 2026-08-26 A14 ruling (see fix_package.py's docstring and
autoeval_check.py): rewriting it would assert Excel authored a file openpyxl
produced. This tool asserts app.xml bytes are identical before and after and
aborts without replacing the file if they are not.

Edits are at ZIP level, member by member; every part except docProps/core.xml
is copied byte for byte, so cached formula values cannot move.
"""
import argparse
import hashlib
import os
import re
import shutil
import sys
import tempfile
import zipfile
from datetime import datetime, timedelta, timezone
from pathlib import Path

CORE = "docProps/core.xml"
APP = "docProps/app.xml"
PYDOCX_DEFAULT_DESC = "generated by python-docx"
FMT = "%Y-%m-%dT%H:%M:%SZ"
STAMP_RE = re.compile(
    r"<dcterms:(created|modified)[^>]*>([^<]*)</dcterms:(?:created|modified)>"
)
DESC_RE = re.compile(r"(<dc:description>)([^<]*)(</dc:description>)")


def read_meta(path: Path):
    with zipfile.ZipFile(path) as z:
        if CORE not in z.namelist():
            return None
        core = z.read(CORE).decode("utf-8")
    stamps = dict(STAMP_RE.findall(core))
    desc = DESC_RE.search(core)
    return {
        "core": core,
        "created": stamps.get("created"),
        "modified": stamps.get("modified"),
        "desc": desc.group(2) if desc else None,
    }


def jitter(name: str, k: int) -> int:
    h = int(hashlib.md5(name.encode()).hexdigest()[:8], 16)
    return 3 + (h % 41) + 17 * k


def decollide(files: dict):
    """files: name -> meta. Shift duplicated stamps; return {name: (created, modified)} changes."""
    changes = {}
    for field in ("created", "modified"):
        seen = {}
        for name in sorted(files):
            val = changes.get(name, {}).get(field) or files[name][field]
            if not val:
                continue
            k = seen.get(val, 0)
            seen[val] = k + 1
            if k == 0:
                continue
            t = datetime.strptime(val, FMT) + timedelta(minutes=jitter(name, k))
            changes.setdefault(name, {})[field] = t.strftime(FMT)
    # keep modified >= created
    for name, ch in changes.items():
        c = ch.get("created") or files[name]["created"]
        m = ch.get("modified") or files[name]["modified"]
        if c and m and m < c:
            ch["modified"] = (datetime.strptime(c, FMT) + timedelta(minutes=jitter(name, 1))).strftime(FMT)
    return changes


def rewrite(path: Path, meta, change) -> str:
    core = meta["core"]
    actions = []
    for field, val in (change or {}).items():
        core = re.sub(
            rf"(<dcterms:{field}[^>]*>)[^<]*(</dcterms:{field}>)",
            rf"\g<1>{val}\g<2>",
            core,
        )
        actions.append(f"{field}->{val}")
    if path.suffix == ".docx" and meta["desc"] == PYDOCX_DEFAULT_DESC:
        core = DESC_RE.sub(lambda m: m.group(1) + m.group(3), core)
        actions.append("desc cleared")
    if core != meta["core"]:
        with zipfile.ZipFile(path) as z:
            names = z.namelist()
            app_before = z.read(APP) if APP in names else None
        fd, tmp = tempfile.mkstemp(suffix=path.suffix, dir=path.parent)
        os.close(fd)
        with zipfile.ZipFile(path) as zin, zipfile.ZipFile(tmp, "w") as zout:
            for info in zin.infolist():
                data = zin.read(info.filename)
                if info.filename == CORE:
                    data = core.encode("utf-8")
                zout.writestr(info, data, compress_type=info.compress_type)
        with zipfile.ZipFile(tmp) as z:
            assert z.namelist() == names, "member list changed - ABORT"
            app_after = z.read(APP) if APP in z.namelist() else None
            assert app_after == app_before, "app.xml moved - ABORT, A14 ruling violated"
        shutil.move(tmp, path)
    # sync mtime to final modified stamp
    m = (change or {}).get("modified") or meta["modified"]
    if m:
        ts = datetime.strptime(m, FMT).replace(tzinfo=timezone.utc).timestamp()
        os.utime(path, (ts, ts))
        actions.append("mtime synced")
    return ", ".join(actions) if actions else "ok (authored stamps kept)"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("folder", help="task folder holding inputs/ and solution/")
    ap.add_argument("--check", action="store_true", help="report the plan without writing")
    args = ap.parse_args()
    root = Path(args.folder)
    files = {}
    for sub in ("inputs", "solution"):
        d = root / sub
        if d.is_dir():
            for f in sorted(d.iterdir()):
                if f.suffix in (".xlsx", ".docx"):
                    meta = read_meta(f)
                    if meta:
                        files[str(f.relative_to(root))] = meta
    if not files:
        sys.exit(f"no xlsx/docx with docProps under {root}/inputs or /solution")
    changes = decollide(files)
    failures = 0
    for name, meta in files.items():
        ch = changes.get(name)
        try:
            if args.check:
                planned = []
                if ch:
                    planned += [f"{k}->{v}" for k, v in ch.items()]
                if name.endswith(".docx") and meta["desc"] == PYDOCX_DEFAULT_DESC:
                    planned.append("desc would clear")
                print(f"[{name}] {', '.join(planned) or 'ok (authored stamps kept)'}")
            else:
                print(f"[{name}] {rewrite(root / name, meta, ch)}")
        except Exception as e:  # noqa: BLE001
            failures += 1
            print(f"[{name}] FAILED: {e}")
    sys.exit(1 if failures else 0)


if __name__ == "__main__":
    main()
