"""Re-save a task's .xlsx/.docx through the real Microsoft Office apps.

    .venv/bin/python tools/office_resave.py <file-or-task-folder>... [--check] [--quiet]

Why this exists (2026-09-02). The june-price-review gate-2 reviewer sent a whole
package back on the docProps generator trace alone: "please open and re-save them
in Excel or LibreOffice so that metadata is cleared". A14 has coded that ever
since. The remedy was blocked because no Office install existed on this machine,
so A14 hits were parked in each task's .gate-debt; the operator installed Word
and Excel on 2026-09-02 and the sanctioned remedy is now available.

This tool performs THAT remedy and only that remedy. It drives Microsoft Excel /
Microsoft Word over AppleScript to open the file and save it, so the application
named in docProps/app.xml is the application that actually wrote the bytes. It
never edits app.xml. Hand-editing the Application/AppVersion pair remains
forbidden under the 2026-08-26 G2a ruling (see fix_package.py, autoeval_check.py
A14): rewriting the string asserts Excel authored a file openpyxl produced, and
leaves the packet exactly as machine-made. A genuine save makes the statement
true instead of forging it.

docProps/core.xml is restored from the pre-resave file, because those fields are
authored in-world properties (the fictional creator, title and timestamps) and
Office would otherwise stamp cp:lastModifiedBy with the operator's real account
name, which is a fresh provenance leak. python-docx's default description
("generated by python-docx") is dropped rather than restored.

Every file is verified after the save and rolled back from a backup if it fails:
formulas and sheet names must be identical for a workbook, and paragraph and
table text identical for a document. Cached formula values are compared too and
reported when they move, since Excel recalculating a cache that openpyxl wrote
is a finding worth seeing rather than a failure.

Run fix_metadata.py afterwards, then rebuild the zips.
"""
import argparse
import re
import shutil
import subprocess
import sys
import zipfile
from pathlib import Path

APP = "docProps/app.xml"
CORE = "docProps/core.xml"
PYDOCX_DEFAULT_DESC = "generated by python-docx"
DESC_RE = re.compile(r"<dc:description>[^<]*</dc:description>")
APP_RE = re.compile(r"<Application>([^<]*)</Application>")
TELLS = ("openpyxl", "python-docx")
# A hand-written Application/AppVersion pair (fix_package.py's old A14 "repair", removed
# under the 2026-08-26 G2a ruling) names an Office app in a stub app.xml carrying nothing
# else. Real Office always writes a fuller part - HeadingPairs/TitlesOfParts for a
# workbook, Template/TotalTime/Pages for a document. Such a file is MORE misleading than
# an openpyxl string, not less: it asserts Excel authored the bytes while removing the
# evidence that it did not, and because it no longer names a python generator it also
# hides from this tool. Detect the stub so the forgery reaches its own remedy.
# (semrad-date-recovery, 2026-09-02: five inputs carried the pair, the solution did not.)
_APP_CHILD_RE = re.compile(rb"<(\w+)[ />]")
_REAL_OFFICE_MARKERS = (b"HeadingPairs", b"TitlesOfParts", b"Template", b"TotalTime",
                        b"DocSecurity", b"Pages", b"Words")

EXCEL = """
tell application "Microsoft Excel"
    set display alerts to false
    set wb to open workbook workbook file name POSIX file "{p}"
    set saved of wb to false
    save wb
    close wb saving no
    set display alerts to true
end tell
"""

WORD = """
tell application "Microsoft Word"
    set display alerts to alerts none
    set doc to open file name POSIX file "{p}"
    set saved of doc to false
    save doc
    close doc saving no
    set display alerts to alerts all
end tell
"""


def props(path: Path) -> str:
    with zipfile.ZipFile(path) as z:
        names = set(z.namelist())
        return "".join(z.read(n).decode("utf-8", "replace")
                       for n in (APP, CORE) if n in names)


def tells_in(path: Path):
    text = props(path).lower()
    return [t for t in TELLS if t in text]


def forged_pair(path):
    """True when app.xml names an Office application in a hand-written stub part."""
    try:
        with zipfile.ZipFile(path) as z:
            if APP not in z.namelist():
                return False
            raw = z.read(APP)
    except Exception:
        return False
    if any(t.encode() in raw.lower() for t in TELLS):
        return False                      # an honest python generator, not a forgery
    app = APP_RE.search(raw.decode("utf-8", "replace"))
    if not app or "microsoft" not in app.group(1).lower():
        return False
    return not any(m in raw for m in _REAL_OFFICE_MARKERS)


def application_of(path: Path) -> str:
    m = APP_RE.search(props(path))
    return m.group(1) if m else "(none)"


def read_part(path: Path, name: str):
    with zipfile.ZipFile(path) as z:
        return z.read(name) if name in z.namelist() else None


def replace_part(path: Path, name: str, data: bytes):
    """Rewrite one zip member, copying every other part byte for byte."""
    tmp = path.with_suffix(path.suffix + ".tmp")
    with zipfile.ZipFile(path) as zin, \
            zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
        wrote = False
        for item in zin.infolist():
            payload = data if item.filename == name else zin.read(item.filename)
            if item.filename == name:
                wrote = True
            zout.writestr(item, payload)
        if not wrote:
            info = zipfile.ZipInfo(name, date_time=zin.infolist()[0].date_time)
            info.compress_type = zipfile.ZIP_DEFLATED
            zout.writestr(info, data)
    tmp.replace(path)


# Excel drops the redundant single quotes openpyxl writes around a sheet name that
# needs none ("='Actions'!A4" saves back as "=Actions!A4"). The reference is the same
# cell either way, and the unquoted form is what a hand-authored workbook holds, so
# the comparison normalises it rather than treating the save as lossy.
QUOTED_SHEET_RE = re.compile(r"'([A-Za-z_][A-Za-z0-9_.]*)'!")


def normalise_formula(value):
    if isinstance(value, str) and value.startswith("="):
        return QUOTED_SHEET_RE.sub(r"\1!", value)
    return value


CALCCHAIN = "xl/calcChain.xml"
CT_CALCCHAIN_RE = re.compile(
    rb'<Override PartName="/xl/calcChain\.xml"[^>]*/>')
REL_CALCCHAIN_RE = re.compile(rb'<Relationship[^>]*calcChain\.xml"[^>]*/>')


def strip_calcchain(path: Path) -> bool:
    """Drop a synthetic xl/calcChain.xml before handing the workbook to Excel.

    fix_package.py writes that part so the authorship extractor's package scan sees
    the formulas (A13). Real Excel is stricter about it than the extractor is: the
    task 42 golden could not be OPENED at all until the part came out ("Parameter
    error", -50). Excel writes its own correct calcChain on save, which is a better
    part than the synthetic one, so this removes it and lets Excel rebuild it.
    """
    with zipfile.ZipFile(path) as z:
        if CALCCHAIN not in z.namelist():
            return False
    tmp = path.with_name(path.stem + ".nocc" + path.suffix)
    with zipfile.ZipFile(path) as zin, \
            zipfile.ZipFile(tmp, "w", zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            if item.filename == CALCCHAIN:
                continue
            data = zin.read(item.filename)
            if item.filename == "[Content_Types].xml":
                data = CT_CALCCHAIN_RE.sub(b"", data)
            elif item.filename == "xl/_rels/workbook.xml.rels":
                data = REL_CALCCHAIN_RE.sub(b"", data)
            zout.writestr(item, data)
    tmp.replace(path)
    return True


WORKBOOK = "xl/workbook.xml"
ABSPATH_RE = re.compile(
    rb"<mc:AlternateContent\b(?:(?!</mc:AlternateContent>).)*?x15ac:absPath"
    rb"(?:(?!</mc:AlternateContent>).)*?</mc:AlternateContent>", re.S)


def strip_abspath(path: Path) -> bool:
    """Remove the folder path Excel stamps into xl/workbook.xml on save.

    Excel records where the file was sitting as <x15ac:absPath url="..."/>, which
    on this machine spells out /Users/<operator>/projects/snk/hazy/... - the
    operator's real account name and the programme's internal codename, shipped
    inside every input workbook. audit_task.py's canary catches the codename. The
    element is a UI convenience hint that says nothing about who wrote the file,
    so dropping it removes a leak without touching the authorship record in
    docProps/app.xml.
    """
    data = read_part(path, WORKBOOK)
    if data is None or b"absPath" not in data:
        return False
    replace_part(path, WORKBOOK, ABSPATH_RE.sub(b"", data))
    return True


def sheet_fingerprint(path: Path, data_only: bool):
    import openpyxl
    wb = openpyxl.load_workbook(path, data_only=data_only)
    out = {}
    for name in wb.sheetnames:
        ws = wb[name]
        for row in ws.iter_rows():
            for cell in row:
                if cell.value is not None:
                    out[(name, cell.coordinate)] = (cell.value if data_only
                                                    else normalise_formula(cell.value))
    wb.close()
    return wb.sheetnames, out


def docx_fingerprint(path: Path):
    import docx
    d = docx.Document(str(path))
    text = [p.text for p in d.paragraphs]
    for table in d.tables:
        for row in table.rows:
            text.extend(c.text for c in row.cells)
    return text


def verify(before: Path, after: Path, log):
    """Return (ok, warnings). Rolls nothing back; the caller owns the backup."""
    warn = []
    if after.suffix.lower() == ".xlsx":
        try:
            names_b, cells_b = sheet_fingerprint(before, False)
            names_a, cells_a = sheet_fingerprint(after, False)
        except Exception as exc:
            return False, [f"unreadable after save: {exc}"]
        if names_b != names_a:
            return False, [f"sheet names moved: {names_b} -> {names_a}"]
        moved = [k for k in set(cells_b) | set(cells_a)
                 if cells_b.get(k) != cells_a.get(k)]
        if moved:
            sample = ", ".join(f"{s}!{c}" for s, c in sorted(moved)[:5])
            return False, [f"{len(moved)} formula/literal cells changed: {sample}"]
        try:
            _, vals_b = sheet_fingerprint(before, True)
            _, vals_a = sheet_fingerprint(after, True)
            drift = [k for k in set(vals_b) | set(vals_a)
                     if vals_b.get(k) != vals_a.get(k)]
            if drift:
                sample = ", ".join(f"{s}!{c} {vals_b.get((s, c))!r}->{vals_a.get((s, c))!r}"
                                   for s, c in sorted(drift)[:5])
                warn.append(f"Excel recalculated {len(drift)} cached values: {sample}")
        except Exception as exc:
            warn.append(f"cached-value comparison skipped: {exc}")
    else:
        try:
            text_b, text_a = docx_fingerprint(before), docx_fingerprint(after)
        except Exception as exc:
            return False, [f"unreadable after save: {exc}"]
        if text_b != text_a:
            diff = next((i for i, (x, y) in enumerate(zip(text_b, text_a)) if x != y),
                        min(len(text_b), len(text_a)))
            return False, [f"document text changed at block {diff}: "
                           f"{text_b[diff:diff + 1]} -> {text_a[diff:diff + 1]}"]
    return True, warn


def resave(path: Path, log) -> bool:
    script = (EXCEL if path.suffix.lower() == ".xlsx" else WORD).format(p=path.resolve())
    backup = path.with_name(f"{path.stem}.pre-resave{path.suffix}")
    shutil.copy2(path, backup)
    core = read_part(path, CORE)
    try:
        if path.suffix.lower() == ".xlsx" and strip_calcchain(path):
            log(f"  note  {path.name}: dropped the synthetic calcChain so Excel can "
                f"rebuild it")
        run = subprocess.run(["osascript", "-e", script],
                             capture_output=True, text=True, timeout=300)
        if run.returncode != 0:
            log(f"  FAIL  {path.name}: Office refused the save: "
                f"{run.stderr.strip().splitlines()[-1] if run.stderr.strip() else run.returncode}")
            backup.replace(path)
            return False
        # A file Office already authored comes back with a byte-identical app.xml
        # (same Application, AppVersion and TitlesOfParts), so "app.xml unchanged" is
        # not proof of a no-op save: a golden edited at zip level after its first Excel
        # save (flyer-program-review, 2026-09-02) was rolled back on that test alone.
        # Office wrote nothing only when the whole package is byte-identical.
        if (read_part(path, APP) == read_part(backup, APP)
                and path.read_bytes() == backup.read_bytes()):
            log(f"  FAIL  {path.name}: Office opened the file but wrote nothing "
                f"(the package is byte-identical) - rolled back")
            backup.replace(path)
            return False
        if core is not None:
            kept = core.decode("utf-8")
            if PYDOCX_DEFAULT_DESC in kept:
                kept = DESC_RE.sub("<dc:description></dc:description>", kept)
            replace_part(path, CORE, kept.encode("utf-8"))
        if path.suffix.lower() == ".xlsx" and strip_abspath(path):
            log(f"  note  {path.name}: stripped the absPath Excel stamped into "
                f"xl/workbook.xml")
        ok, warn = verify(backup, path, log)
        if not ok:
            log(f"  FAIL  {path.name}: {warn[0]} - rolled back")
            backup.replace(path)
            return False
        left = tells_in(path)
        if left:
            log(f"  FAIL  {path.name}: docProps still names {'/'.join(left)} "
                f"after the save - rolled back")
            backup.replace(path)
            return False
        for line in warn:
            log(f"  note  {path.name}: {line}")
        log(f"  ok    {path.name}: Application={application_of(path)}")
        backup.unlink()
        return True
    except subprocess.TimeoutExpired:
        log(f"  FAIL  {path.name}: Office did not answer in 300s - rolled back")
        backup.replace(path)
        return False


def targets(args):
    seen = []
    for raw in args:
        p = Path(raw)
        if p.is_dir():
            for sub in ("inputs", "solution"):
                d = p / sub
                if d.is_dir():
                    seen += sorted(q for q in d.iterdir()
                                   if q.suffix.lower() in (".xlsx", ".docx")
                                   and not q.name.startswith("~$")
                                   and ".pre-resave" not in q.name)
        elif p.suffix.lower() in (".xlsx", ".docx"):
            seen.append(p)
    return seen


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("paths", nargs="+", help="task folders or individual .xlsx/.docx files")
    ap.add_argument("--check", action="store_true",
                    help="report which files still name a python generator, save nothing")
    ap.add_argument("--quiet", action="store_true", help="print only failures and the tally")
    ap.add_argument("--force", action="store_true",
                    help="resave every target, even one whose docProps already look clean")
    args = ap.parse_args()

    lines = []

    def log(line):
        lines.append(line)
        if not args.quiet or line.lstrip().startswith("FAIL"):
            print(line)

    files = targets(args.paths)
    if not files:
        print("no .xlsx/.docx found under those paths")
        return 1

    if args.check:
        dirty = 0
        for f in files:
            t = tells_in(f)
            if t:
                dirty += 1
                print(f"  TELL  {f}: docProps names {'/'.join(t)} "
                      f"(Application={application_of(f)})")
            elif forged_pair(f):
                dirty += 1
                print(f"  FORGED {f}: hand-written Application pair "
                      f"({application_of(f)}) in a stub app.xml, no Office ever wrote it")
        print(f"{dirty} of {len(files)} files name a python generator")
        return 1 if dirty else 0

    done = failed = skipped = 0
    for f in files:
        if not (args.force or tells_in(f) or forged_pair(f)):
            skipped += 1
            continue
        print(f"{f}")
        if resave(f, log):
            done += 1
        else:
            failed += 1
    print(f"\nresaved {done}, failed {failed}, already clean {skipped}")
    print("next: fix_metadata.py on each task folder, then rebuild the i-/s- zips")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
